version: '3'
services:
    api_gamification:
      build: .
      restart: always
      links:
        - database
      volumes:
        - .:/usr/src/app/
      ports:
        - 5000:5000
      depends_on:
        - database

    database:
        build: ./services/mysql/.
        command: --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;'
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: M1TN3xT0
          MYSQL_DATABASE: gamification_nexto
          DB_HOST: database
        volumes:
          - db-volume:/var/lib/mysql
volumes:
    db-volume: