apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  labels:
    type: local
  namespace: mit-gamification
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"