---
apiVersion: v1
kind: Service
metadata:
  name: gamification-svc
  labels:
    app: gamification
  namespace: mit-gamification
spec:
  selector:
    app: gamification
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer